#!/bin/bash

USER=$(whoami)
vncserver -list
echo "Mematikan Server VNC"
echo -n "Masukkan port yang ingin dimatikan (ex :2): "
read pt
echo " "
echo "Mematikan port $pt"
vncserver -kill :$pt
rm -rf /tmp/.X$pt-lock
rm -rf /tmp/.X11-unix/X$pt
