#!/data/data/com.termux/files/usr/bin/bash
pkg update -y && pkg upgrade
pkg install x11-repo
pkg install xfce* tigervnc
mkdir .themes
mkdir .icons
mkdir .vnc

echo "#!/data/data/com.termux/files/usr/bin/bash
## This file is executed during VNC server
## startup.

# Launch terminal emulator Aterm.
# Requires package 'aterm'.
aterm -geometry 80x24+10+10 -ls &

# Launch Tab Window Manager.
# Requires package 'xorg-twm'.
twm &
startxfce4 &" >> $HOME/.vnc/xstartup
chmod +x $HOME/.vnc/xstartup

echo "#!/data/data/com.termux/files/usr/bin/bash
vncserver -localhost  $GEO :$PORT
VNC server started. The default password is the account password for $USER" >> $PREFIX/bin/vnc

echo "#!/data/data/com.termux/files/usr/bin/bash
export USER=$(whoami)
HEIGHT=0
WIDTH=0
CHOICE_HEIGHT=6
BACKTITLE="Pilih resolusi Linux vncserver"
TITLE="vncserver-start"
MENU="Pilih salah satu:"
export PORT=1

OPTIONS=(1 "Automatis/dynamic"
         2 "Potrait 610 x 1140"
         3 "Potrait 680 x 1400"
         4 "Lanscape HD 1400 x 680"
         5 "Lanscape FHD 2200 x 1080"
         6 "Resolusi dan port manual")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            echo "Resolusi dinamis"
            GEO="" vnc
            ;;
        2)
            echo "Potrait 610 x 1250"
            GEO="-geometry 610x1140" vnc
            ;;
        3)
            echo "Potrait 680 x 1400"
            GEO="-geometry 680x1400" vnc
            ;;
        4)
            echo "Lanscape HD 1400 x 680"
            GEO="-geometry 1400x680" vnc
            ;;
        5)
            echo "Lanscape FHD 2200 x 1080"
            GEO="-geometry 2200x1080" vnc
            ;;
        6)
            echo "Resolusi dan port manual"
            echo "Masukkan resolusi dalam format WIDTHxHEIGHT i.e 1920x1080"
            read custom
            echo "Masukkan port i.e 2"
            read port
            GEO="-geometry $custom" PORT=$port vnc
            ;;
esac" >>$PREFIX/bin/tstart

echo "#!/data/data/com.termux/files/usr/bin/bash
USER=$(whoami)
vncserver -list
echo "Mematikan Server VNC"
vncserver -kill :1
rm -rf /tmp/.X1-lock
rm -rf /tmp/.X11-unix/X1" >>$PREFIX/bin/tstop

chmod +x $PREFIX/bin/vnc
chmod +x $PREFIX/bin/tstart
chmod +x $PREFIX/bin/tstop

echo "Anda sekarang dapat memulai vncserver dengan menjalankan tstart"
echo " "
echo "Ini akan meminta Anda untuk memasukkan kata sandi saat pertama kali memulainya."
echo " "
echo "Server VNC akan dimulai pada 127.0.0.1:5901"
echo " "
echo "Anda dapat terhubung ke alamat ini dengan VNC Viewer yang Anda inginkan"
echo " "
echo "Hubungkan ke alamat ini akan membuka jendela dengan Lingkungan Desktop Xfce4"
echo " "
echo " "
echo "Menjalankan tstart"
echo " "
echo " "
echo "Untuk Membunuh Server VNC jalankan tstop"
echo " "
echo " "

vncpasswd
tstart
